" Plugins instalados:
" - CtrlP: Simula o CTRL+P do sublime para buscas rapidas   (https://github.com/ctrlpvim/ctrlp.vim)
" - tcomment: Simula o CTRL+/ para comentario de linhas     (https://github.com/tomtom/tcomment_vim)
" - Completor.vim: plugin de autocomplete (DESATIVADO)      (https://github.com/maralla/completor.vim)

"==========================================
" Configuracoes diversas
"==========================================
set t_Co=256        "Informa suporte a 256 cores
set encoding=utf8
set ruler           "Mostra linha:coluna
set mouse=a	        "Ativa o suporte ao mouse (para selecionar texto p.e.)
set hidden          "Permite mudar de buffer sem salvar as alterações realizadas
set nocompatible    "Desabilita compatibilidade com VI
set number 	        "Mostra numero da linha
set nowrap	        "Desabilita quebra de linha
set expandtab	    "Troca tabs por espaços
set tabstop=4	    "Quantidade de espaços do tab
set shiftwidth=4    "Quantidade de espaços do tab
set softtabstop=4   "Faz o backspace tratar 4 espaços como tab
set backspace=indent,eol,start
set ignorecase	    "Buscas case insensitive
set incsearch	    "Destaca resultado da busca enquanto digita
set hlsearch        "Destaca todas as ocorrencias da busca
set showmatch	    "Mostra o casamento de {}, [] e ()
set nobackup	    "Desabilita o uso de arquivos de backup
set nostartofline   "Permanece na mesma coluna ao mudar de linha
set warn            " Warning when a shell cmd is used while the buffer has been changed.
set shm+=I          " Start without the intro message
set shm+=s          " Suppress 'search hit BOTTOM, continuing at TOP' message
set shm+=tT         " Truncate long filenames/messages
set nowritebackup
set noswapfile
set dictionary=/usr/share/dict/words,/usr/share/dict/brazilian
set complete+=k
set ttyfast
set laststatus=2    "Always show the statusline
set scrolloff=2     "Mostra pelo menos 2 linhas acima e abaixo do cursor
set sidescroll=1    " min. number of columns to scroll horizontally.
set sidescrolloff=2 " min. number of columns to keep to the left/right of the cursor
set fillchars=stl:\=,stlnc:\-,vert:\|,fold:-,diff:-
set wildmenu
set wildmode=full
set foldmethod=marker
set foldenable
set splitbelow
set splitright
set noerrorbells
set novisualbell
set nomodeline
set t_vb=
set spell spelllang=en,pt
" set cursorline

"StatusLine configuration
set statusline= "Limpa qualquer definição anterior
set statusline+=%#LineNr#               "Seta a cor do grupo 'LineNr'
set statusline+=%f                      "Path do arquivo no buffer atual
set statusline+=\ %m                    "Flag indicando se o arquivo foi modificado '[+]'
set statusline+=%=                      "Marca o fim dos itens alinhados a esquerda e inicio dos alinhados a direita
set statusline+=%#Special#              "Seta a cor do grupo 'Special'
set statusline+=\ %y                    "Espaço em branco e o tipo do arquivo
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}  "Espaço em branco e tipo de encoding
set statusline+=\ \[%{&fileformat}\]    "Espaço em branco e o formato do arquivo 'unix/dos'
set statusline+=\ %p%%                  "Percentagem do arquivo
set statusline+=\ %l:%c                 "Linha e coluna
set statusline+=\                       "Espaço em branco

"==========================================
"Desativa a troca de tab por espaços quando o arquivo for um makefile
"==========================================
autocmd FileType make setlocal noexpandtab


"==========================================
"Configuração do navegador de arquivos
"==========================================
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25


"==========================================
"Atalhos e/ou mapeamentos de teclado
"==========================================

"Mapeamentos do modo normal: Redimensionar splits
" nmap <C-Left> <C-w><
" nmap <C-Right> <C-w>>
" nmap <C-Up> <C-W>+<C-W>+
" nmap <C-Down> <C-W>-<C-W>-
nmap <space> viw
nmap - dd

"Mapeamentos do modo de inserção
inoremap <c-w> <ESC>:w<CR>
inoremap " ""<left>
inoremap ' ''<left>
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O

"F1: aciona o help para a palavra sob o cursor
"F3: limpa o destaque nas palavras após uma busca
noremap  <F1> :help <C-r><C-w><CR>
noremap  <F3> :set hlsearch! hlsearch?<CR> 
noremap  <F5> :source ~/.vimrc<CR>
noremap  <F4> :bd<CR>
noremap  <S-F4> :bd!<CR>
nnoremap <C-Left> <ESC>:bp<CR>
nnoremap <C-Right> <ESC>:bn<CR>

"==========================================
"Comandos
"==========================================
"Uma pequena mensagem ao iniciar...
augroup greeting
    autocmd!
    autocmd VimEnter * :echo "Olá Ricardo  >^.^<"
augroup END

"Ativa o reconhecimento de sintaxe e padrão de cores
filetype plugin on
syntax on           
colorscheme vimdark

"==========================================
"modificações de cores
"==========================================
"Altera a cor do auto-complete de rosa para cinza
" highlight Pmenu      cterm=none  ctermbg=gray       ctermfg=black
" highlight PmenuSel   cterm=none  ctermbg=darkgray   ctermfg=white
" highlight VertSplit  cterm=none  ctermbg=black      ctermfg=White
" highlight Search     cterm=none  ctermbg=darkyellow ctermfg=black
" highlight MatchParen cterm=none  ctermbg=none       ctermfg=red
" highlight SpellBad   cterm=none  ctermbg=darkgray   ctermfg=darkred
highlight EndOfBuffer ctermbg=black ctermfg=black guibg=black guifg=black
highlight SpellBad    ctermbg=black ctermfg=darkred

