" Configuracoes diversas {{{

set t_Co=256        "Informa suporte a 256 cores
set encoding=utf8
set ruler           "Mostra linha:coluna
set mouse=a         "Ativa o suporte ao mouse (para selecionar texto p.e.)
set hidden          "Permite mudar de buffer sem salvar as alterações realizadas
set nocompatible    "Desabilita compatibilidade com VI
set number          "Mostra numero da linha
set relativenumber  "Mostra numero da linha de forma hibrida (relativa mas mostrando a atual)
set nowrap          "Desabilita quebra de linha
set wrapscan        "Search wrap at the end of the file
set breakindent     "Ao quebrar a linha, manter a identação
set expandtab	    "Troca tabs por espaços
set tabstop=4	    "Quantidade de espaços do tab
set shiftwidth=4    "Quantidade de espaços do tab
set softtabstop=4   "Faz o backspace tratar 4 espaços como tab
set backspace=indent,eol,start
set ignorecase	    "Buscas case insensitive
set incsearch	    "Destaca resultado da busca enquanto digita
set hlsearch        "Destaca todas as ocorrencias da busca
set showmatch	    "Mostra o casamento de {}, [] e ()
set nobackup	    "Desabilita o uso de arquivos de backup
set nostartofline   "Permanece na mesma coluna ao mudar de linha
set warn            "Warning when a shell cmd is used while the buffer has been changed.
set shortmess+=I    "Start without the intro message
set shortmess+=s    "Suppress 'search hit BOTTOM, continuing at TOP' message
set shortmess+=tT   "Truncate long filenames/messages
set shortmess+=a    "Truncate long filenames/messages
set nowritebackup   "Do not create backupfile
set noswapfile      "Do not create a swapfile
set dictionary=/usr/share/dict/words,/usr/share/dict/brazilian
set complete+=k
set ttyfast
set laststatus=2    " Always show the statusline
set scrolloff=2     " Mostra pelo menos 2 linhas acima e abaixo do cursor
set sidescroll=1    " min. number of columns to scroll horizontally.
set sidescrolloff=2 " min. number of columns to keep to the left/right of the cursor
set path+=**        " Search down into subfolders. Provides tab-completion for all file-related tasks
set wildmenu        " Display all matching files when we tab complete
set wildmode=full
set wildignore+=*.so,*~,*/.git/*
set foldmethod=syntax
set nofoldenable
set splitbelow
set splitright
set noerrorbells
set novisualbell
set nomodeline
set t_vb=
" set spell spelllang=en,pt
" set cursorline
set confirm
set history=2000
set timeoutlen=500
set showmatch       " Jump to matching bracket
set matchpairs+=<:> " Add HTML brackets to pair matching
set matchtime=1     " Tenths of a second to show the matching paren
set list
set fillchars=stl:\=,stlnc:\-,vert:\|,fold:-,diff:-
" set listchars=tab:»·,nbsp:+,trail:.,extends:→,precedes:←,space:\ ,eol:<
set listchars=tab:»·,trail:.,extends:→,precedes:←,space:\ ,nbsp:+
set statusline= "Limpa qualquer definição anterior
set statusline+=%#LineNr#               "Seta a cor do grupo 'LineNr'
set statusline+=%f                      "Path do arquivo no buffer atual
set statusline+=\ %m                    "Flag indicando se o arquivo foi modificado '[+]'
" set statusline+=\[%{FugitiveHead()}\]  "Indica o branch do arquivo atual
set statusline+=%=                      "Marca o fim dos itens alinhados a esquerda e inicio dos alinhados a direita
set statusline+=%#Special#              "Seta a cor do grupo 'Special'
set statusline+=\ %y                    "Espaço em branco e o tipo do arquivo
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}  "Espaço em branco e tipo de encoding
set statusline+=\ \[%{&fileformat}\]    "Espaço em branco e o formato do arquivo 'unix/dos'
set statusline+=\ %p%%                  "Percentagem do arquivo
set statusline+=\ %l:%c                 "Linha e coluna
set statusline+=\                       "Espaço em branco

" sign define atention text=ᐅᐅ linehl=Warning texthl=Error
" ✓ ֍ ᐅ ‣  ⃟ ⇒ ⎊ ⏵⏵ ▷ ☛ ⚑ ⚐ ⚠
" syntax keyword pyConstant None conceal cchar=∅

"}}}

" Configuração de plugins {{{

" Install and run vim-plug on first run
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Install the plugins on this list
source ~/.vim/plugins.vim

" TagList config
let Tlist_GainFocus_On_ToggleOpen = 1
let Tlist_Show_One_File = 1
let Tlist_Use_Right_Window = 1
let Tlist_Use_SingleClick = 1
let Tlist_Compact_Format = 1
let Tlist_Enable_Fold_Column = 0
let Tlist_WinWidth = 33

"}}}

" Mapeamentos de tecla {{{

"Mapeamentos do modo normal: Redimensionar splits
map <C-_> :TComment<CR>
nmap <C-S-Left> <C-w><
nmap <C-S-Right> <C-w>>
" nmap <C-Up> <C-W>+<C-W>+
" nmap <C-Down> <C-W>-<C-W>-
nmap <space> viw
nmap - dd
nmap " ciw"<ESC>p
nmap ' `

"Mapeamentos do modo de inserção
" inoremap <c-w> <ESC>:w<CR>
inoremap " ""<left>
inoremap ' ''<left>
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O

"F3: limpa o destaque nas palavras após uma busca
nnoremap <silent> <F3> :set hlsearch! hlsearch?<CR>
nnoremap <silent> <F4> :bd<CR>
nnoremap <F5> :source ~/.vim/vimrc<CR>

nnoremap <silent> <F7> :cn<CR>
nnoremap <silent> <F8> :cp<CR>
nnoremap <silent> <F9> :Make<CR>
nnoremap <silent> <F10> :TlistToggle<CR>

nnoremap <S-F4> :bd!<CR>
nnoremap <C-Left> <ESC>:bp<CR>
nnoremap <C-Right> <ESC>:bn<CR>
nnoremap <C-p> :Files <cr>
nnoremap <C-g> :Rg <cr>

" shortcuts for 3-way merge
map <Leader>1 :diffget LOCAL<CR>
map <Leader>2 :diffget BASE<CR>
map <Leader>3 :diffget REMOTE<CR>

"}}}

" Comandos {{{

"Uma pequena mensagem ao iniciar...
augroup greeting
    autocmd!
    autocmd VimEnter * :echo "Olá Ricardo  >^.^<"
augroup END

augroup configgroup
    autocmd!
    "Desativa a troca de tab por espaços quando o arquivo for um makefile
    autocmd BufEnter Makefile setlocal noexpandtab
    autocmd BufWritePost *.c exe ":Dispatch! ctags -R ."
augroup END

"}}}

" Modificações de cor e sintaxe {{{

"Ativa o reconhecimento de sintaxe e padrão de cores
filetype plugin on
syntax on
colorscheme vimdark

" Altera definições de cor
highlight EndOfBuffer ctermbg=black ctermfg=black guibg=black guifg=black
highlight SpellBad    ctermbg=black ctermfg=darkred
highlight SpellCap    ctermbg=black ctermfg=yellow
highlight MatchWord   ctermbg=black ctermfg=white

highlight MyTagListFileName ctermfg=darkred ctermbg=black
highlight MyTagListTitle    ctermfg=white   ctermbg=black
highlight MyTagListTagName  ctermfg=blue    ctermbg=black
" highlight MyTagListComment  ctermfg= 		ctermbg=black
" highlight MyTagListTagScope ctermfg=darkred	ctermbg=black

"}}}
