#xbacklight -set 50 &
xsetroot -solid darkslategrey &
setxkbmap br &
numlockx &

xload -geometry +1-20  -update 1 -nolabel -jumpscroll 1 -bg darkslategrey -bw 0 -bd darkslategrey &
xterm -geometry 260x68+10+10 -e tmux &
#st -g 200x50+20+20 -e "tmux" -f "-misc-dejavu sans mono-medium-*-normal-*-*-*-*-*-*-*-*-*"

exec cwm

