alias lss='ls -lhSF --color=always --group-directories-first --time-style=+"[%d/%m/%Y %T]"'
alias ctl='systemctl'
alias ctlu='systemctl --user'
alias sctl='sudo systemctl'
alias pstop="ps -A --sort -rsz -o comm,pmem,pcpu | awk 'NR<=20'"
alias meuip="dig +short myip.opendns.com @resolver1.opendns.com"
alias clip="curl -F 'sprunge=<-' http://sprunge.us"

alias doc="sudo docker"

alias pac="pacman"
alias spac="sudo pacman"

alias gc='git commit'
alias gd='git diff'
alias gl='git log -20 --oneline'
alias gll='git log -10'
alias gs='git status --untracked-files=no'
alias gss='git status'

