#!/bin/sh

alias lss='ls -lhSF --color=always --group-directories-first --time-style=+"[%d/%m/%Y %T]"'
alias ll="(printf 'Permissões Links Dono Grupo Bytes Mês Dia '; printf 'Hora/Ano Arquivo\n'; ls -lhSF --color=always --group-directories-first | sed 1d) | column -t"
alias ctl='systemctl'
alias ctlu='systemctl --user'
alias sctl='sudo systemctl'
alias pstop="ps -A --sort -rsz -o comm,pmem,pcpu | awk 'NR<=20'"
alias meuip="dig +short myip.opendns.com @resolver1.opendns.com"
alias clip="curl -F 'sprunge=<-' http://sprunge.us"

alias pac="pacman"
alias spac="sudo pacman"

alias gc='git commit'
alias gd='git diff'
alias gl="git log --color --oneline | fzf --multi --reverse --preview 'git show --color {+1}'"
alias gll='git log -10'
alias glc='git log --color --oneline --name-status -10'
alias gs='git status --untracked-files=no'
alias gss='git status'
alias gr='git pull --rebase --autostash origin master'
alias rankmirrors="sudo reflector -c 'Brazil' -a 12 --sort rate --save /etc/pacman.d/mirrorlist"
